set dir "/data/user/shared_projects/chalmers/mal/simulations/dimer/analyses/9-md_MD2_2microsec_done/caver_2.0/pdbB"

mol load pdb ${dir}/frame0.pdb
animate read pdb ${dir}/frame1.pdb
animate read pdb ${dir}/frame2.pdb
animate read pdb ${dir}/frame3.pdb
animate read pdb ${dir}/frame4.pdb
animate read pdb ${dir}/frame5.pdb
animate read pdb ${dir}/frame6.pdb
animate read pdb ${dir}/frame7.pdb
animate read pdb ${dir}/frame8.pdb
animate read pdb ${dir}/frame9.pdb
animate read pdb ${dir}/frame10.pdb
animate read pdb ${dir}/frame11.pdb
animate read pdb ${dir}/frame12.pdb
animate read pdb ${dir}/frame13.pdb
animate read pdb ${dir}/frame14.pdb
animate read pdb ${dir}/frame15.pdb
animate read pdb ${dir}/frame16.pdb
animate read pdb ${dir}/frame17.pdb
animate read pdb ${dir}/frame18.pdb
animate read pdb ${dir}/frame19.pdb
animate read pdb ${dir}/frame20.pdb
animate read pdb ${dir}/frame21.pdb
animate read pdb ${dir}/frame22.pdb
animate read pdb ${dir}/frame23.pdb
animate read pdb ${dir}/frame24.pdb
animate read pdb ${dir}/frame25.pdb
animate read pdb ${dir}/frame26.pdb
animate read pdb ${dir}/frame27.pdb
animate read pdb ${dir}/frame28.pdb
animate read pdb ${dir}/frame29.pdb
animate read pdb ${dir}/frame30.pdb
animate read pdb ${dir}/frame31.pdb
animate read pdb ${dir}/frame32.pdb
animate read pdb ${dir}/frame33.pdb
animate read pdb ${dir}/frame34.pdb
animate read pdb ${dir}/frame35.pdb
animate read pdb ${dir}/frame36.pdb
animate read pdb ${dir}/frame37.pdb
animate read pdb ${dir}/frame38.pdb
animate read pdb ${dir}/frame39.pdb
animate read pdb ${dir}/frame40.pdb
animate read pdb ${dir}/frame41.pdb
animate read pdb ${dir}/frame42.pdb
animate read pdb ${dir}/frame43.pdb
animate read pdb ${dir}/frame44.pdb
animate read pdb ${dir}/frame45.pdb
animate read pdb ${dir}/frame46.pdb
animate read pdb ${dir}/frame47.pdb
animate read pdb ${dir}/frame48.pdb
animate read pdb ${dir}/frame49.pdb
animate read pdb ${dir}/frame50.pdb
animate read pdb ${dir}/frame51.pdb
animate read pdb ${dir}/frame52.pdb
animate read pdb ${dir}/frame53.pdb
animate read pdb ${dir}/frame54.pdb
animate read pdb ${dir}/frame55.pdb
animate read pdb ${dir}/frame56.pdb
animate read pdb ${dir}/frame57.pdb
animate read pdb ${dir}/frame58.pdb
animate read pdb ${dir}/frame59.pdb
animate read pdb ${dir}/frame60.pdb
animate read pdb ${dir}/frame61.pdb
animate read pdb ${dir}/frame62.pdb
animate read pdb ${dir}/frame63.pdb
animate read pdb ${dir}/frame64.pdb
animate read pdb ${dir}/frame65.pdb
animate read pdb ${dir}/frame66.pdb
animate read pdb ${dir}/frame67.pdb
animate read pdb ${dir}/frame68.pdb
animate read pdb ${dir}/frame69.pdb
animate read pdb ${dir}/frame70.pdb
animate read pdb ${dir}/frame71.pdb
animate read pdb ${dir}/frame72.pdb
animate read pdb ${dir}/frame73.pdb
animate read pdb ${dir}/frame74.pdb
animate read pdb ${dir}/frame75.pdb
animate read pdb ${dir}/frame76.pdb
animate read pdb ${dir}/frame77.pdb
animate read pdb ${dir}/frame78.pdb
animate read pdb ${dir}/frame79.pdb
animate read pdb ${dir}/frame80.pdb
animate read pdb ${dir}/frame81.pdb
animate read pdb ${dir}/frame82.pdb
animate read pdb ${dir}/frame83.pdb
animate read pdb ${dir}/frame84.pdb
animate read pdb ${dir}/frame85.pdb
animate read pdb ${dir}/frame86.pdb
animate read pdb ${dir}/frame87.pdb
animate read pdb ${dir}/frame88.pdb
animate read pdb ${dir}/frame89.pdb
animate read pdb ${dir}/frame90.pdb
animate read pdb ${dir}/frame91.pdb
animate read pdb ${dir}/frame92.pdb
animate read pdb ${dir}/frame93.pdb
animate read pdb ${dir}/frame94.pdb
animate read pdb ${dir}/frame95.pdb
animate read pdb ${dir}/frame96.pdb
animate read pdb ${dir}/frame97.pdb
animate read pdb ${dir}/frame98.pdb
animate read pdb ${dir}/frame99.pdb
animate read pdb ${dir}/frame100.pdb
animate read pdb ${dir}/frame101.pdb
animate read pdb ${dir}/frame102.pdb
animate read pdb ${dir}/frame103.pdb
animate read pdb ${dir}/frame104.pdb
animate read pdb ${dir}/frame105.pdb
animate read pdb ${dir}/frame106.pdb
animate read pdb ${dir}/frame107.pdb
animate read pdb ${dir}/frame108.pdb
animate read pdb ${dir}/frame109.pdb
animate read pdb ${dir}/frame110.pdb
animate read pdb ${dir}/frame111.pdb
animate read pdb ${dir}/frame112.pdb
animate read pdb ${dir}/frame113.pdb
animate read pdb ${dir}/frame114.pdb
animate read pdb ${dir}/frame115.pdb
animate read pdb ${dir}/frame116.pdb
animate read pdb ${dir}/frame117.pdb
animate read pdb ${dir}/frame118.pdb
animate read pdb ${dir}/frame119.pdb
animate read pdb ${dir}/frame120.pdb
animate read pdb ${dir}/frame121.pdb
animate read pdb ${dir}/frame122.pdb
animate read pdb ${dir}/frame123.pdb
animate read pdb ${dir}/frame124.pdb
animate read pdb ${dir}/frame125.pdb
animate read pdb ${dir}/frame126.pdb
animate read pdb ${dir}/frame127.pdb
animate read pdb ${dir}/frame128.pdb
animate read pdb ${dir}/frame129.pdb
animate read pdb ${dir}/frame130.pdb
animate read pdb ${dir}/frame131.pdb
animate read pdb ${dir}/frame132.pdb
animate read pdb ${dir}/frame133.pdb
animate read pdb ${dir}/frame134.pdb
animate read pdb ${dir}/frame135.pdb
animate read pdb ${dir}/frame136.pdb
animate read pdb ${dir}/frame137.pdb
animate read pdb ${dir}/frame138.pdb
animate read pdb ${dir}/frame139.pdb
animate read pdb ${dir}/frame140.pdb
animate read pdb ${dir}/frame141.pdb
animate read pdb ${dir}/frame142.pdb
animate read pdb ${dir}/frame143.pdb
animate read pdb ${dir}/frame144.pdb
animate read pdb ${dir}/frame145.pdb
animate read pdb ${dir}/frame146.pdb
animate read pdb ${dir}/frame147.pdb
animate read pdb ${dir}/frame148.pdb
animate read pdb ${dir}/frame149.pdb
animate read pdb ${dir}/frame150.pdb
animate read pdb ${dir}/frame151.pdb
animate read pdb ${dir}/frame152.pdb
animate read pdb ${dir}/frame153.pdb
animate read pdb ${dir}/frame154.pdb
animate read pdb ${dir}/frame155.pdb
animate read pdb ${dir}/frame156.pdb
animate read pdb ${dir}/frame157.pdb
animate read pdb ${dir}/frame158.pdb
animate read pdb ${dir}/frame159.pdb
animate read pdb ${dir}/frame160.pdb
animate read pdb ${dir}/frame161.pdb
animate read pdb ${dir}/frame162.pdb
animate read pdb ${dir}/frame163.pdb
animate read pdb ${dir}/frame164.pdb
animate read pdb ${dir}/frame165.pdb
animate read pdb ${dir}/frame166.pdb
animate read pdb ${dir}/frame167.pdb
animate read pdb ${dir}/frame168.pdb
animate read pdb ${dir}/frame169.pdb
animate read pdb ${dir}/frame170.pdb
animate read pdb ${dir}/frame171.pdb
animate read pdb ${dir}/frame172.pdb
animate read pdb ${dir}/frame173.pdb
animate read pdb ${dir}/frame174.pdb
animate read pdb ${dir}/frame175.pdb
animate read pdb ${dir}/frame176.pdb
animate read pdb ${dir}/frame177.pdb
animate read pdb ${dir}/frame178.pdb
animate read pdb ${dir}/frame179.pdb
animate read pdb ${dir}/frame180.pdb
animate read pdb ${dir}/frame181.pdb
animate read pdb ${dir}/frame182.pdb
animate read pdb ${dir}/frame183.pdb
animate read pdb ${dir}/frame184.pdb
animate read pdb ${dir}/frame185.pdb
animate read pdb ${dir}/frame186.pdb
animate read pdb ${dir}/frame187.pdb
animate read pdb ${dir}/frame188.pdb
animate read pdb ${dir}/frame189.pdb
animate read pdb ${dir}/frame190.pdb
animate read pdb ${dir}/frame191.pdb
animate read pdb ${dir}/frame192.pdb
animate read pdb ${dir}/frame193.pdb
animate read pdb ${dir}/frame194.pdb
animate read pdb ${dir}/frame195.pdb
animate read pdb ${dir}/frame196.pdb
animate read pdb ${dir}/frame197.pdb
animate read pdb ${dir}/frame198.pdb
animate read pdb ${dir}/frame199.pdb
animate read pdb ${dir}/frame200.pdb
animate read pdb ${dir}/frame201.pdb
animate read pdb ${dir}/frame202.pdb
animate read pdb ${dir}/frame203.pdb
animate read pdb ${dir}/frame204.pdb
animate read pdb ${dir}/frame205.pdb
animate read pdb ${dir}/frame206.pdb
animate read pdb ${dir}/frame207.pdb
animate read pdb ${dir}/frame208.pdb
animate read pdb ${dir}/frame209.pdb
animate read pdb ${dir}/frame210.pdb
animate read pdb ${dir}/frame211.pdb
animate read pdb ${dir}/frame212.pdb
animate read pdb ${dir}/frame213.pdb
animate read pdb ${dir}/frame214.pdb
animate read pdb ${dir}/frame215.pdb
animate read pdb ${dir}/frame216.pdb
animate read pdb ${dir}/frame217.pdb
animate read pdb ${dir}/frame218.pdb
animate read pdb ${dir}/frame219.pdb
animate read pdb ${dir}/frame220.pdb
animate read pdb ${dir}/frame221.pdb
animate read pdb ${dir}/frame222.pdb
animate read pdb ${dir}/frame223.pdb
animate read pdb ${dir}/frame224.pdb
animate read pdb ${dir}/frame225.pdb
animate read pdb ${dir}/frame226.pdb
animate read pdb ${dir}/frame227.pdb
animate read pdb ${dir}/frame228.pdb
animate read pdb ${dir}/frame229.pdb
animate read pdb ${dir}/frame230.pdb
animate read pdb ${dir}/frame231.pdb
animate read pdb ${dir}/frame232.pdb
animate read pdb ${dir}/frame233.pdb
animate read pdb ${dir}/frame234.pdb
animate read pdb ${dir}/frame235.pdb
animate read pdb ${dir}/frame236.pdb
animate read pdb ${dir}/frame237.pdb
animate read pdb ${dir}/frame238.pdb
animate read pdb ${dir}/frame239.pdb
animate read pdb ${dir}/frame240.pdb
animate read pdb ${dir}/frame241.pdb
animate read pdb ${dir}/frame242.pdb
animate read pdb ${dir}/frame243.pdb
animate read pdb ${dir}/frame244.pdb
animate read pdb ${dir}/frame245.pdb
animate read pdb ${dir}/frame246.pdb
animate read pdb ${dir}/frame247.pdb
animate read pdb ${dir}/frame248.pdb
animate read pdb ${dir}/frame249.pdb
animate read pdb ${dir}/frame250.pdb
animate read pdb ${dir}/frame251.pdb
animate read pdb ${dir}/frame252.pdb
animate read pdb ${dir}/frame253.pdb
animate read pdb ${dir}/frame254.pdb
animate read pdb ${dir}/frame255.pdb
animate read pdb ${dir}/frame256.pdb
animate read pdb ${dir}/frame257.pdb
animate read pdb ${dir}/frame258.pdb
animate read pdb ${dir}/frame259.pdb
animate read pdb ${dir}/frame260.pdb
animate read pdb ${dir}/frame261.pdb
animate read pdb ${dir}/frame262.pdb
animate read pdb ${dir}/frame263.pdb
animate read pdb ${dir}/frame264.pdb
animate read pdb ${dir}/frame265.pdb
animate read pdb ${dir}/frame266.pdb
animate read pdb ${dir}/frame267.pdb
animate read pdb ${dir}/frame268.pdb
animate read pdb ${dir}/frame269.pdb
animate read pdb ${dir}/frame270.pdb
animate read pdb ${dir}/frame271.pdb
animate read pdb ${dir}/frame272.pdb
animate read pdb ${dir}/frame273.pdb
animate read pdb ${dir}/frame274.pdb
animate read pdb ${dir}/frame275.pdb
animate read pdb ${dir}/frame276.pdb
animate read pdb ${dir}/frame277.pdb
animate read pdb ${dir}/frame278.pdb
animate read pdb ${dir}/frame279.pdb
animate read pdb ${dir}/frame280.pdb
animate read pdb ${dir}/frame281.pdb
animate read pdb ${dir}/frame282.pdb
animate read pdb ${dir}/frame283.pdb
animate read pdb ${dir}/frame284.pdb
animate read pdb ${dir}/frame285.pdb
animate read pdb ${dir}/frame286.pdb
animate read pdb ${dir}/frame287.pdb
animate read pdb ${dir}/frame288.pdb
animate read pdb ${dir}/frame289.pdb
animate read pdb ${dir}/frame290.pdb
animate read pdb ${dir}/frame291.pdb
animate read pdb ${dir}/frame292.pdb
animate read pdb ${dir}/frame293.pdb
animate read pdb ${dir}/frame294.pdb
animate read pdb ${dir}/frame295.pdb
animate read pdb ${dir}/frame296.pdb
animate read pdb ${dir}/frame297.pdb
animate read pdb ${dir}/frame298.pdb
animate read pdb ${dir}/frame299.pdb
animate read pdb ${dir}/frame300.pdb
animate read pdb ${dir}/frame301.pdb
animate read pdb ${dir}/frame302.pdb
animate read pdb ${dir}/frame303.pdb
animate read pdb ${dir}/frame304.pdb
animate read pdb ${dir}/frame305.pdb
animate read pdb ${dir}/frame306.pdb
animate read pdb ${dir}/frame307.pdb
animate read pdb ${dir}/frame308.pdb
animate read pdb ${dir}/frame309.pdb
animate read pdb ${dir}/frame310.pdb
animate read pdb ${dir}/frame311.pdb
animate read pdb ${dir}/frame312.pdb
animate read pdb ${dir}/frame313.pdb
animate read pdb ${dir}/frame314.pdb
animate read pdb ${dir}/frame315.pdb
animate read pdb ${dir}/frame316.pdb
animate read pdb ${dir}/frame317.pdb
animate read pdb ${dir}/frame318.pdb
animate read pdb ${dir}/frame319.pdb
animate read pdb ${dir}/frame320.pdb
animate read pdb ${dir}/frame321.pdb
animate read pdb ${dir}/frame322.pdb
animate read pdb ${dir}/frame323.pdb
animate read pdb ${dir}/frame324.pdb
animate read pdb ${dir}/frame325.pdb
animate read pdb ${dir}/frame326.pdb
animate read pdb ${dir}/frame327.pdb
animate read pdb ${dir}/frame328.pdb
animate read pdb ${dir}/frame329.pdb
animate read pdb ${dir}/frame330.pdb
animate read pdb ${dir}/frame331.pdb
animate read pdb ${dir}/frame332.pdb
animate read pdb ${dir}/frame333.pdb
animate read pdb ${dir}/frame334.pdb
animate read pdb ${dir}/frame335.pdb
animate read pdb ${dir}/frame336.pdb
animate read pdb ${dir}/frame337.pdb
animate read pdb ${dir}/frame338.pdb
animate read pdb ${dir}/frame339.pdb
animate read pdb ${dir}/frame340.pdb
animate read pdb ${dir}/frame341.pdb
animate read pdb ${dir}/frame342.pdb
animate read pdb ${dir}/frame343.pdb
animate read pdb ${dir}/frame344.pdb
animate read pdb ${dir}/frame345.pdb
animate read pdb ${dir}/frame346.pdb
animate read pdb ${dir}/frame347.pdb
animate read pdb ${dir}/frame348.pdb
animate read pdb ${dir}/frame349.pdb
animate read pdb ${dir}/frame350.pdb
animate read pdb ${dir}/frame351.pdb
animate read pdb ${dir}/frame352.pdb
animate read pdb ${dir}/frame353.pdb
animate read pdb ${dir}/frame354.pdb
animate read pdb ${dir}/frame355.pdb
animate read pdb ${dir}/frame356.pdb
animate read pdb ${dir}/frame357.pdb
animate read pdb ${dir}/frame358.pdb
animate read pdb ${dir}/frame359.pdb
animate read pdb ${dir}/frame360.pdb
animate read pdb ${dir}/frame361.pdb
animate read pdb ${dir}/frame362.pdb
animate read pdb ${dir}/frame363.pdb
animate read pdb ${dir}/frame364.pdb
animate read pdb ${dir}/frame365.pdb
animate read pdb ${dir}/frame366.pdb
animate read pdb ${dir}/frame367.pdb
animate read pdb ${dir}/frame368.pdb
animate read pdb ${dir}/frame369.pdb
animate read pdb ${dir}/frame370.pdb
animate read pdb ${dir}/frame371.pdb
animate read pdb ${dir}/frame372.pdb
animate read pdb ${dir}/frame373.pdb
animate read pdb ${dir}/frame374.pdb
animate read pdb ${dir}/frame375.pdb
animate read pdb ${dir}/frame376.pdb
animate read pdb ${dir}/frame377.pdb
animate read pdb ${dir}/frame378.pdb
animate read pdb ${dir}/frame379.pdb
animate read pdb ${dir}/frame380.pdb
animate read pdb ${dir}/frame381.pdb
animate read pdb ${dir}/frame382.pdb
animate read pdb ${dir}/frame383.pdb
animate read pdb ${dir}/frame384.pdb
animate read pdb ${dir}/frame385.pdb
animate read pdb ${dir}/frame386.pdb
animate read pdb ${dir}/frame387.pdb
animate read pdb ${dir}/frame388.pdb
animate read pdb ${dir}/frame389.pdb
animate read pdb ${dir}/frame390.pdb
animate read pdb ${dir}/frame391.pdb
animate read pdb ${dir}/frame392.pdb
animate read pdb ${dir}/frame393.pdb
animate read pdb ${dir}/frame394.pdb
animate read pdb ${dir}/frame395.pdb
animate read pdb ${dir}/frame396.pdb
animate read pdb ${dir}/frame397.pdb
animate read pdb ${dir}/frame398.pdb
animate read pdb ${dir}/frame399.pdb
animate read pdb ${dir}/frame400.pdb
animate read pdb ${dir}/frame401.pdb
animate read pdb ${dir}/frame402.pdb
animate read pdb ${dir}/frame403.pdb
animate read pdb ${dir}/frame404.pdb
animate read pdb ${dir}/frame405.pdb
animate read pdb ${dir}/frame406.pdb
animate read pdb ${dir}/frame407.pdb
animate read pdb ${dir}/frame408.pdb
animate read pdb ${dir}/frame409.pdb
animate read pdb ${dir}/frame410.pdb
animate read pdb ${dir}/frame411.pdb
animate read pdb ${dir}/frame412.pdb
animate read pdb ${dir}/frame413.pdb
animate read pdb ${dir}/frame414.pdb
animate read pdb ${dir}/frame415.pdb
animate read pdb ${dir}/frame416.pdb
animate read pdb ${dir}/frame417.pdb
animate read pdb ${dir}/frame418.pdb
animate read pdb ${dir}/frame419.pdb
animate read pdb ${dir}/frame420.pdb
animate read pdb ${dir}/frame421.pdb
animate read pdb ${dir}/frame422.pdb
animate read pdb ${dir}/frame423.pdb
animate read pdb ${dir}/frame424.pdb
animate read pdb ${dir}/frame425.pdb
animate read pdb ${dir}/frame426.pdb
animate read pdb ${dir}/frame427.pdb
animate read pdb ${dir}/frame428.pdb
animate read pdb ${dir}/frame429.pdb
animate read pdb ${dir}/frame430.pdb
animate read pdb ${dir}/frame431.pdb
animate read pdb ${dir}/frame432.pdb
animate read pdb ${dir}/frame433.pdb
animate read pdb ${dir}/frame434.pdb
animate read pdb ${dir}/frame435.pdb
animate read pdb ${dir}/frame436.pdb
animate read pdb ${dir}/frame437.pdb
animate read pdb ${dir}/frame438.pdb
animate read pdb ${dir}/frame439.pdb
animate read pdb ${dir}/frame440.pdb
animate read pdb ${dir}/frame441.pdb
animate read pdb ${dir}/frame442.pdb
animate read pdb ${dir}/frame443.pdb
animate read pdb ${dir}/frame444.pdb
animate read pdb ${dir}/frame445.pdb
animate read pdb ${dir}/frame446.pdb
animate read pdb ${dir}/frame447.pdb
animate read pdb ${dir}/frame448.pdb
animate read pdb ${dir}/frame449.pdb
animate read pdb ${dir}/frame450.pdb
animate read pdb ${dir}/frame451.pdb
animate read pdb ${dir}/frame452.pdb
animate read pdb ${dir}/frame453.pdb
animate read pdb ${dir}/frame454.pdb
animate read pdb ${dir}/frame455.pdb
animate read pdb ${dir}/frame456.pdb
animate read pdb ${dir}/frame457.pdb
animate read pdb ${dir}/frame458.pdb
animate read pdb ${dir}/frame459.pdb
animate read pdb ${dir}/frame460.pdb
animate read pdb ${dir}/frame461.pdb
animate read pdb ${dir}/frame462.pdb
animate read pdb ${dir}/frame463.pdb
animate read pdb ${dir}/frame464.pdb
animate read pdb ${dir}/frame465.pdb
animate read pdb ${dir}/frame466.pdb
animate read pdb ${dir}/frame467.pdb
animate read pdb ${dir}/frame468.pdb
animate read pdb ${dir}/frame469.pdb
animate read pdb ${dir}/frame470.pdb
animate read pdb ${dir}/frame471.pdb
animate read pdb ${dir}/frame472.pdb
animate read pdb ${dir}/frame473.pdb
animate read pdb ${dir}/frame474.pdb
animate read pdb ${dir}/frame475.pdb
animate read pdb ${dir}/frame476.pdb
animate read pdb ${dir}/frame477.pdb
animate read pdb ${dir}/frame478.pdb
animate read pdb ${dir}/frame479.pdb
animate read pdb ${dir}/frame480.pdb
animate read pdb ${dir}/frame481.pdb
animate read pdb ${dir}/frame482.pdb
animate read pdb ${dir}/frame483.pdb
animate read pdb ${dir}/frame484.pdb
animate read pdb ${dir}/frame485.pdb
animate read pdb ${dir}/frame486.pdb
animate read pdb ${dir}/frame487.pdb
animate read pdb ${dir}/frame488.pdb
animate read pdb ${dir}/frame489.pdb
animate read pdb ${dir}/frame490.pdb
animate read pdb ${dir}/frame491.pdb
animate read pdb ${dir}/frame492.pdb
animate read pdb ${dir}/frame493.pdb
animate read pdb ${dir}/frame494.pdb
animate read pdb ${dir}/frame495.pdb
animate read pdb ${dir}/frame496.pdb
animate read pdb ${dir}/frame497.pdb
animate read pdb ${dir}/frame498.pdb
animate read pdb ${dir}/frame499.pdb
animate read pdb ${dir}/frame500.pdb
animate read pdb ${dir}/frame501.pdb
animate read pdb ${dir}/frame502.pdb
animate read pdb ${dir}/frame503.pdb
animate read pdb ${dir}/frame504.pdb
animate read pdb ${dir}/frame505.pdb
animate read pdb ${dir}/frame506.pdb
animate read pdb ${dir}/frame507.pdb
animate read pdb ${dir}/frame508.pdb
animate read pdb ${dir}/frame509.pdb
animate read pdb ${dir}/frame510.pdb
animate read pdb ${dir}/frame511.pdb
animate read pdb ${dir}/frame512.pdb
animate read pdb ${dir}/frame513.pdb
animate read pdb ${dir}/frame514.pdb
animate read pdb ${dir}/frame515.pdb
animate read pdb ${dir}/frame516.pdb
animate read pdb ${dir}/frame517.pdb
animate read pdb ${dir}/frame518.pdb
animate read pdb ${dir}/frame519.pdb
animate read pdb ${dir}/frame520.pdb
animate read pdb ${dir}/frame521.pdb
animate read pdb ${dir}/frame522.pdb
animate read pdb ${dir}/frame523.pdb
animate read pdb ${dir}/frame524.pdb
animate read pdb ${dir}/frame525.pdb
animate read pdb ${dir}/frame526.pdb
animate read pdb ${dir}/frame527.pdb
animate read pdb ${dir}/frame528.pdb
animate read pdb ${dir}/frame529.pdb
animate read pdb ${dir}/frame530.pdb
animate read pdb ${dir}/frame531.pdb
animate read pdb ${dir}/frame532.pdb
animate read pdb ${dir}/frame533.pdb
animate read pdb ${dir}/frame534.pdb
animate read pdb ${dir}/frame535.pdb
animate read pdb ${dir}/frame536.pdb
animate read pdb ${dir}/frame537.pdb
animate read pdb ${dir}/frame538.pdb
animate read pdb ${dir}/frame539.pdb
animate read pdb ${dir}/frame540.pdb
animate read pdb ${dir}/frame541.pdb
animate read pdb ${dir}/frame542.pdb
animate read pdb ${dir}/frame543.pdb
animate read pdb ${dir}/frame544.pdb
animate read pdb ${dir}/frame545.pdb
animate read pdb ${dir}/frame546.pdb
animate read pdb ${dir}/frame547.pdb
animate read pdb ${dir}/frame548.pdb
animate read pdb ${dir}/frame549.pdb
animate read pdb ${dir}/frame550.pdb
animate read pdb ${dir}/frame551.pdb
animate read pdb ${dir}/frame552.pdb
animate read pdb ${dir}/frame553.pdb
animate read pdb ${dir}/frame554.pdb
animate read pdb ${dir}/frame555.pdb
animate read pdb ${dir}/frame556.pdb
animate read pdb ${dir}/frame557.pdb
animate read pdb ${dir}/frame558.pdb
animate read pdb ${dir}/frame559.pdb
animate read pdb ${dir}/frame560.pdb
animate read pdb ${dir}/frame561.pdb
animate read pdb ${dir}/frame562.pdb
animate read pdb ${dir}/frame563.pdb
animate read pdb ${dir}/frame564.pdb
animate read pdb ${dir}/frame565.pdb
animate read pdb ${dir}/frame566.pdb
animate read pdb ${dir}/frame567.pdb
animate read pdb ${dir}/frame568.pdb
animate read pdb ${dir}/frame569.pdb
animate read pdb ${dir}/frame570.pdb
animate read pdb ${dir}/frame571.pdb
animate read pdb ${dir}/frame572.pdb
animate read pdb ${dir}/frame573.pdb
animate read pdb ${dir}/frame574.pdb
animate read pdb ${dir}/frame575.pdb
animate read pdb ${dir}/frame576.pdb
animate read pdb ${dir}/frame577.pdb
animate read pdb ${dir}/frame578.pdb
animate read pdb ${dir}/frame579.pdb
animate read pdb ${dir}/frame580.pdb
animate read pdb ${dir}/frame581.pdb
animate read pdb ${dir}/frame582.pdb
animate read pdb ${dir}/frame583.pdb
animate read pdb ${dir}/frame584.pdb
animate read pdb ${dir}/frame585.pdb
animate read pdb ${dir}/frame586.pdb
animate read pdb ${dir}/frame587.pdb
animate read pdb ${dir}/frame588.pdb
animate read pdb ${dir}/frame589.pdb
animate read pdb ${dir}/frame590.pdb
animate read pdb ${dir}/frame591.pdb
animate read pdb ${dir}/frame592.pdb
animate read pdb ${dir}/frame593.pdb
animate read pdb ${dir}/frame594.pdb
animate read pdb ${dir}/frame595.pdb
animate read pdb ${dir}/frame596.pdb
animate read pdb ${dir}/frame597.pdb
animate read pdb ${dir}/frame598.pdb
animate read pdb ${dir}/frame599.pdb
animate read pdb ${dir}/frame600.pdb
animate read pdb ${dir}/frame601.pdb
animate read pdb ${dir}/frame602.pdb
animate read pdb ${dir}/frame603.pdb
animate read pdb ${dir}/frame604.pdb
animate read pdb ${dir}/frame605.pdb
animate read pdb ${dir}/frame606.pdb
animate read pdb ${dir}/frame607.pdb
animate read pdb ${dir}/frame608.pdb
animate read pdb ${dir}/frame609.pdb
animate read pdb ${dir}/frame610.pdb
animate read pdb ${dir}/frame611.pdb
animate read pdb ${dir}/frame612.pdb
animate read pdb ${dir}/frame613.pdb
animate read pdb ${dir}/frame614.pdb
animate read pdb ${dir}/frame615.pdb
animate read pdb ${dir}/frame616.pdb
animate read pdb ${dir}/frame617.pdb
animate read pdb ${dir}/frame618.pdb
animate read pdb ${dir}/frame619.pdb
animate read pdb ${dir}/frame620.pdb
animate read pdb ${dir}/frame621.pdb
animate read pdb ${dir}/frame622.pdb
animate read pdb ${dir}/frame623.pdb
animate read pdb ${dir}/frame624.pdb
animate read pdb ${dir}/frame625.pdb
animate read pdb ${dir}/frame626.pdb
animate read pdb ${dir}/frame627.pdb
animate read pdb ${dir}/frame628.pdb
animate read pdb ${dir}/frame629.pdb
animate read pdb ${dir}/frame630.pdb
animate read pdb ${dir}/frame631.pdb
animate read pdb ${dir}/frame632.pdb
animate read pdb ${dir}/frame633.pdb
animate read pdb ${dir}/frame634.pdb
animate read pdb ${dir}/frame635.pdb
animate read pdb ${dir}/frame636.pdb
animate read pdb ${dir}/frame637.pdb
animate read pdb ${dir}/frame638.pdb
animate read pdb ${dir}/frame639.pdb
animate read pdb ${dir}/frame640.pdb
animate read pdb ${dir}/frame641.pdb
animate read pdb ${dir}/frame642.pdb
animate read pdb ${dir}/frame643.pdb
animate read pdb ${dir}/frame644.pdb
animate read pdb ${dir}/frame645.pdb
animate read pdb ${dir}/frame646.pdb
animate read pdb ${dir}/frame647.pdb
animate read pdb ${dir}/frame648.pdb
animate read pdb ${dir}/frame649.pdb
animate read pdb ${dir}/frame650.pdb
animate read pdb ${dir}/frame651.pdb
animate read pdb ${dir}/frame652.pdb
animate read pdb ${dir}/frame653.pdb
animate read pdb ${dir}/frame654.pdb
animate read pdb ${dir}/frame655.pdb
animate read pdb ${dir}/frame656.pdb
animate read pdb ${dir}/frame657.pdb
animate read pdb ${dir}/frame658.pdb
animate read pdb ${dir}/frame659.pdb
animate read pdb ${dir}/frame660.pdb
animate read pdb ${dir}/frame661.pdb
animate read pdb ${dir}/frame662.pdb
animate read pdb ${dir}/frame663.pdb
animate read pdb ${dir}/frame664.pdb
animate read pdb ${dir}/frame665.pdb
animate read pdb ${dir}/frame666.pdb
animate read pdb ${dir}/frame667.pdb
animate read pdb ${dir}/frame668.pdb
animate read pdb ${dir}/frame669.pdb
animate read pdb ${dir}/frame670.pdb
animate read pdb ${dir}/frame671.pdb
animate read pdb ${dir}/frame672.pdb
animate read pdb ${dir}/frame673.pdb
animate read pdb ${dir}/frame674.pdb
animate read pdb ${dir}/frame675.pdb
animate read pdb ${dir}/frame676.pdb
animate read pdb ${dir}/frame677.pdb
animate read pdb ${dir}/frame678.pdb
animate read pdb ${dir}/frame679.pdb
animate read pdb ${dir}/frame680.pdb
animate read pdb ${dir}/frame681.pdb
animate read pdb ${dir}/frame682.pdb
animate read pdb ${dir}/frame683.pdb
animate read pdb ${dir}/frame684.pdb
animate read pdb ${dir}/frame685.pdb
animate read pdb ${dir}/frame686.pdb
animate read pdb ${dir}/frame687.pdb
animate read pdb ${dir}/frame688.pdb
animate read pdb ${dir}/frame689.pdb
animate read pdb ${dir}/frame690.pdb
animate read pdb ${dir}/frame691.pdb
animate read pdb ${dir}/frame692.pdb
animate read pdb ${dir}/frame693.pdb
animate read pdb ${dir}/frame694.pdb
animate read pdb ${dir}/frame695.pdb
animate read pdb ${dir}/frame696.pdb
animate read pdb ${dir}/frame697.pdb
animate read pdb ${dir}/frame698.pdb
animate read pdb ${dir}/frame699.pdb
animate read pdb ${dir}/frame700.pdb
animate read pdb ${dir}/frame701.pdb
animate read pdb ${dir}/frame702.pdb
animate read pdb ${dir}/frame703.pdb
animate read pdb ${dir}/frame704.pdb
animate read pdb ${dir}/frame705.pdb
animate read pdb ${dir}/frame706.pdb
animate read pdb ${dir}/frame707.pdb
animate read pdb ${dir}/frame708.pdb
animate read pdb ${dir}/frame709.pdb
animate read pdb ${dir}/frame710.pdb
animate read pdb ${dir}/frame711.pdb
animate read pdb ${dir}/frame712.pdb
animate read pdb ${dir}/frame713.pdb
animate read pdb ${dir}/frame714.pdb
animate read pdb ${dir}/frame715.pdb
animate read pdb ${dir}/frame716.pdb
animate read pdb ${dir}/frame717.pdb
animate read pdb ${dir}/frame718.pdb
animate read pdb ${dir}/frame719.pdb
animate read pdb ${dir}/frame720.pdb
animate read pdb ${dir}/frame721.pdb
animate read pdb ${dir}/frame722.pdb
animate read pdb ${dir}/frame723.pdb
animate read pdb ${dir}/frame724.pdb
animate read pdb ${dir}/frame725.pdb
animate read pdb ${dir}/frame726.pdb
animate read pdb ${dir}/frame727.pdb
animate read pdb ${dir}/frame728.pdb
animate read pdb ${dir}/frame729.pdb
animate read pdb ${dir}/frame730.pdb
animate read pdb ${dir}/frame731.pdb
animate read pdb ${dir}/frame732.pdb
animate read pdb ${dir}/frame733.pdb
animate read pdb ${dir}/frame734.pdb
animate read pdb ${dir}/frame735.pdb
animate read pdb ${dir}/frame736.pdb
animate read pdb ${dir}/frame737.pdb
animate read pdb ${dir}/frame738.pdb
animate read pdb ${dir}/frame739.pdb
animate read pdb ${dir}/frame740.pdb
animate read pdb ${dir}/frame741.pdb
animate read pdb ${dir}/frame742.pdb
animate read pdb ${dir}/frame743.pdb
animate read pdb ${dir}/frame744.pdb
animate read pdb ${dir}/frame745.pdb
animate read pdb ${dir}/frame746.pdb
animate read pdb ${dir}/frame747.pdb
animate read pdb ${dir}/frame748.pdb
animate read pdb ${dir}/frame749.pdb
animate read pdb ${dir}/frame750.pdb
animate read pdb ${dir}/frame751.pdb
animate read pdb ${dir}/frame752.pdb
animate read pdb ${dir}/frame753.pdb
animate read pdb ${dir}/frame754.pdb
animate read pdb ${dir}/frame755.pdb
animate read pdb ${dir}/frame756.pdb
animate read pdb ${dir}/frame757.pdb
animate read pdb ${dir}/frame758.pdb
animate read pdb ${dir}/frame759.pdb
animate read pdb ${dir}/frame760.pdb
animate read pdb ${dir}/frame761.pdb
animate read pdb ${dir}/frame762.pdb
animate read pdb ${dir}/frame763.pdb
animate read pdb ${dir}/frame764.pdb
animate read pdb ${dir}/frame765.pdb
animate read pdb ${dir}/frame766.pdb
animate read pdb ${dir}/frame767.pdb
animate read pdb ${dir}/frame768.pdb
animate read pdb ${dir}/frame769.pdb
animate read pdb ${dir}/frame770.pdb
animate read pdb ${dir}/frame771.pdb
animate read pdb ${dir}/frame772.pdb
animate read pdb ${dir}/frame773.pdb
animate read pdb ${dir}/frame774.pdb
animate read pdb ${dir}/frame775.pdb
animate read pdb ${dir}/frame776.pdb
animate read pdb ${dir}/frame777.pdb
animate read pdb ${dir}/frame778.pdb
animate read pdb ${dir}/frame779.pdb
animate read pdb ${dir}/frame780.pdb
animate read pdb ${dir}/frame781.pdb
animate read pdb ${dir}/frame782.pdb
animate read pdb ${dir}/frame783.pdb
animate read pdb ${dir}/frame784.pdb
animate read pdb ${dir}/frame785.pdb
animate read pdb ${dir}/frame786.pdb
animate read pdb ${dir}/frame787.pdb
animate read pdb ${dir}/frame788.pdb
animate read pdb ${dir}/frame789.pdb
animate read pdb ${dir}/frame790.pdb
animate read pdb ${dir}/frame791.pdb
animate read pdb ${dir}/frame792.pdb
animate read pdb ${dir}/frame793.pdb
animate read pdb ${dir}/frame794.pdb
animate read pdb ${dir}/frame795.pdb
animate read pdb ${dir}/frame796.pdb
animate read pdb ${dir}/frame797.pdb
animate read pdb ${dir}/frame798.pdb
animate read pdb ${dir}/frame799.pdb
animate read pdb ${dir}/frame800.pdb
animate read pdb ${dir}/frame801.pdb
animate read pdb ${dir}/frame802.pdb
animate read pdb ${dir}/frame803.pdb
animate read pdb ${dir}/frame804.pdb
animate read pdb ${dir}/frame805.pdb
animate read pdb ${dir}/frame806.pdb
animate read pdb ${dir}/frame807.pdb
animate read pdb ${dir}/frame808.pdb
animate read pdb ${dir}/frame809.pdb
animate read pdb ${dir}/frame810.pdb
animate read pdb ${dir}/frame811.pdb
animate read pdb ${dir}/frame812.pdb
animate read pdb ${dir}/frame813.pdb
animate read pdb ${dir}/frame814.pdb
animate read pdb ${dir}/frame815.pdb
animate read pdb ${dir}/frame816.pdb
animate read pdb ${dir}/frame817.pdb
animate read pdb ${dir}/frame818.pdb
animate read pdb ${dir}/frame819.pdb
animate read pdb ${dir}/frame820.pdb
animate read pdb ${dir}/frame821.pdb
animate read pdb ${dir}/frame822.pdb
animate read pdb ${dir}/frame823.pdb
animate read pdb ${dir}/frame824.pdb
animate read pdb ${dir}/frame825.pdb
animate read pdb ${dir}/frame826.pdb
animate read pdb ${dir}/frame827.pdb
animate read pdb ${dir}/frame828.pdb
animate read pdb ${dir}/frame829.pdb
animate read pdb ${dir}/frame830.pdb
animate read pdb ${dir}/frame831.pdb
animate read pdb ${dir}/frame832.pdb
animate read pdb ${dir}/frame833.pdb
animate read pdb ${dir}/frame834.pdb
animate read pdb ${dir}/frame835.pdb
animate read pdb ${dir}/frame836.pdb
animate read pdb ${dir}/frame837.pdb
animate read pdb ${dir}/frame838.pdb
animate read pdb ${dir}/frame839.pdb
animate read pdb ${dir}/frame840.pdb
animate read pdb ${dir}/frame841.pdb
animate read pdb ${dir}/frame842.pdb
animate read pdb ${dir}/frame843.pdb
animate read pdb ${dir}/frame844.pdb
animate read pdb ${dir}/frame845.pdb
animate read pdb ${dir}/frame846.pdb
animate read pdb ${dir}/frame847.pdb
animate read pdb ${dir}/frame848.pdb
animate read pdb ${dir}/frame849.pdb
animate read pdb ${dir}/frame850.pdb
animate read pdb ${dir}/frame851.pdb
animate read pdb ${dir}/frame852.pdb
animate read pdb ${dir}/frame853.pdb
animate read pdb ${dir}/frame854.pdb
animate read pdb ${dir}/frame855.pdb
animate read pdb ${dir}/frame856.pdb
animate read pdb ${dir}/frame857.pdb
animate read pdb ${dir}/frame858.pdb
animate read pdb ${dir}/frame859.pdb
animate read pdb ${dir}/frame860.pdb
animate read pdb ${dir}/frame861.pdb
animate read pdb ${dir}/frame862.pdb
animate read pdb ${dir}/frame863.pdb
animate read pdb ${dir}/frame864.pdb
animate read pdb ${dir}/frame865.pdb
animate read pdb ${dir}/frame866.pdb
animate read pdb ${dir}/frame867.pdb
animate read pdb ${dir}/frame868.pdb
animate read pdb ${dir}/frame869.pdb
animate read pdb ${dir}/frame870.pdb
animate read pdb ${dir}/frame871.pdb
animate read pdb ${dir}/frame872.pdb
animate read pdb ${dir}/frame873.pdb
animate read pdb ${dir}/frame874.pdb
animate read pdb ${dir}/frame875.pdb
animate read pdb ${dir}/frame876.pdb
animate read pdb ${dir}/frame877.pdb
animate read pdb ${dir}/frame878.pdb
animate read pdb ${dir}/frame879.pdb
animate read pdb ${dir}/frame880.pdb
animate read pdb ${dir}/frame881.pdb
animate read pdb ${dir}/frame882.pdb
animate read pdb ${dir}/frame883.pdb
animate read pdb ${dir}/frame884.pdb
animate read pdb ${dir}/frame885.pdb
animate read pdb ${dir}/frame886.pdb
animate read pdb ${dir}/frame887.pdb
animate read pdb ${dir}/frame888.pdb
animate read pdb ${dir}/frame889.pdb
animate read pdb ${dir}/frame890.pdb
animate read pdb ${dir}/frame891.pdb
animate read pdb ${dir}/frame892.pdb
animate read pdb ${dir}/frame893.pdb
animate read pdb ${dir}/frame894.pdb
animate read pdb ${dir}/frame895.pdb
animate read pdb ${dir}/frame896.pdb
animate read pdb ${dir}/frame897.pdb
animate read pdb ${dir}/frame898.pdb
animate read pdb ${dir}/frame899.pdb
animate read pdb ${dir}/frame900.pdb
animate read pdb ${dir}/frame901.pdb
animate read pdb ${dir}/frame902.pdb
animate read pdb ${dir}/frame903.pdb
animate read pdb ${dir}/frame904.pdb
animate read pdb ${dir}/frame905.pdb
animate read pdb ${dir}/frame906.pdb
animate read pdb ${dir}/frame907.pdb
animate read pdb ${dir}/frame908.pdb
animate read pdb ${dir}/frame909.pdb
animate read pdb ${dir}/frame910.pdb
animate read pdb ${dir}/frame911.pdb
animate read pdb ${dir}/frame912.pdb
animate read pdb ${dir}/frame913.pdb
animate read pdb ${dir}/frame914.pdb
animate read pdb ${dir}/frame915.pdb
animate read pdb ${dir}/frame916.pdb
animate read pdb ${dir}/frame917.pdb
animate read pdb ${dir}/frame918.pdb
animate read pdb ${dir}/frame919.pdb
animate read pdb ${dir}/frame920.pdb
animate read pdb ${dir}/frame921.pdb
animate read pdb ${dir}/frame922.pdb
animate read pdb ${dir}/frame923.pdb
animate read pdb ${dir}/frame924.pdb
animate read pdb ${dir}/frame925.pdb
animate read pdb ${dir}/frame926.pdb
animate read pdb ${dir}/frame927.pdb
animate read pdb ${dir}/frame928.pdb
animate read pdb ${dir}/frame929.pdb
animate read pdb ${dir}/frame930.pdb
animate read pdb ${dir}/frame931.pdb
animate read pdb ${dir}/frame932.pdb
animate read pdb ${dir}/frame933.pdb
animate read pdb ${dir}/frame934.pdb
animate read pdb ${dir}/frame935.pdb
animate read pdb ${dir}/frame936.pdb
animate read pdb ${dir}/frame937.pdb
animate read pdb ${dir}/frame938.pdb
animate read pdb ${dir}/frame939.pdb
animate read pdb ${dir}/frame940.pdb
animate read pdb ${dir}/frame941.pdb
animate read pdb ${dir}/frame942.pdb
animate read pdb ${dir}/frame943.pdb
animate read pdb ${dir}/frame944.pdb
animate read pdb ${dir}/frame945.pdb
animate read pdb ${dir}/frame946.pdb
animate read pdb ${dir}/frame947.pdb
animate read pdb ${dir}/frame948.pdb
animate read pdb ${dir}/frame949.pdb
animate read pdb ${dir}/frame950.pdb
animate read pdb ${dir}/frame951.pdb
animate read pdb ${dir}/frame952.pdb
animate read pdb ${dir}/frame953.pdb
animate read pdb ${dir}/frame954.pdb
animate read pdb ${dir}/frame955.pdb
animate read pdb ${dir}/frame956.pdb
animate read pdb ${dir}/frame957.pdb
animate read pdb ${dir}/frame958.pdb
animate read pdb ${dir}/frame959.pdb
animate read pdb ${dir}/frame960.pdb
animate read pdb ${dir}/frame961.pdb
animate read pdb ${dir}/frame962.pdb
animate read pdb ${dir}/frame963.pdb
animate read pdb ${dir}/frame964.pdb
animate read pdb ${dir}/frame965.pdb
animate read pdb ${dir}/frame966.pdb
animate read pdb ${dir}/frame967.pdb
animate read pdb ${dir}/frame968.pdb
animate read pdb ${dir}/frame969.pdb
animate read pdb ${dir}/frame970.pdb
animate read pdb ${dir}/frame971.pdb
animate read pdb ${dir}/frame972.pdb
animate read pdb ${dir}/frame973.pdb
animate read pdb ${dir}/frame974.pdb
animate read pdb ${dir}/frame975.pdb
animate read pdb ${dir}/frame976.pdb
animate read pdb ${dir}/frame977.pdb
animate read pdb ${dir}/frame978.pdb
animate read pdb ${dir}/frame979.pdb
animate read pdb ${dir}/frame980.pdb
animate read pdb ${dir}/frame981.pdb
animate read pdb ${dir}/frame982.pdb
animate read pdb ${dir}/frame983.pdb
animate read pdb ${dir}/frame984.pdb
animate read pdb ${dir}/frame985.pdb
animate read pdb ${dir}/frame986.pdb
animate read pdb ${dir}/frame987.pdb
animate read pdb ${dir}/frame988.pdb
animate read pdb ${dir}/frame989.pdb
animate read pdb ${dir}/frame990.pdb
animate read pdb ${dir}/frame991.pdb
animate read pdb ${dir}/frame992.pdb
animate read pdb ${dir}/frame993.pdb
animate read pdb ${dir}/frame994.pdb
animate read pdb ${dir}/frame995.pdb
animate read pdb ${dir}/frame996.pdb
animate read pdb ${dir}/frame997.pdb
animate read pdb ${dir}/frame998.pdb
animate read pdb ${dir}/frame999.pdb

after idle { 
  mol representation NewCartoon 
  mol delrep 0 top
  mol addrep top
  mol modcolor 0 top "ColorID" 8
} 

